Fix pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -7,7 +7,10 @@
 set -e
 
 echo "Checking for submodule commits not pushed"
-if [[ $(git submodule foreach --quiet 'git diff --stat main origin/main') ]]; then
+CHNG=$(git submodule foreach --quiet 'git diff --stat main origin/main')
+if [[ $? != 0 ]]; then
+    echo "Command failed."
+elif [[ $CHNG ]]; then
     echo "Submodules not pushed"
     exit 1
 else
